version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack -c release
test_script:
- cmd: dotnet test .\YahooFinanceApi.Tests\YahooFinanceApi.Tests.csproj
artifacts:
- path: YahooFinanceApi/bin/Release/YahooFinanceApi.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: acSSgAlUNA/OCqX0TVICWNqcNcYgBJi01ynOZwXGhTNGVNtRQiv4FIJFsoYnuSgB
  on:
    branch: master
